# Generated by Django 4.2.4 on 2023-11-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_imdbvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Awards',
        ),
    ]
